ansible_python_interpreter: /usr/bin/python3
ansible_user: seed
ansible_ssh_pass: dees
ansible_ssh_common_args: '-o PubkeyAuthentication=no -o PreferredAuthentications=password -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa'
